---
description: Cover - Office - Positioning
alias: cover_office_positioning
id: 417cff74-9b15-4848-9050-a3cfe18007e1
mode: restart
trigger:
  - platform: time_pattern
    minutes: "/10"
  - platform: event
    event_type:
      - timer.cancelled
      - timer.finished
    event_data:
      entity_id: timer.cover_office
condition:
  - condition: state
    entity_id: timer.cover_office
    state: "idle"
  - condition: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(states.cover.shelly_2_5_rc_office.last_changed) | int(0)) > (states('input_number.cover_office_detection') | int) }}"
action:
  - condition: template
    value_template: "{{ not is_state('input_select.covers_mode', 'Manuel') }}"
  - condition: template
    value_template: "{{ not is_state('input_select.cover_office_mode', 'Manuel') }}"
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.presence_at_home
            state: "off"
          - condition: state
            entity_id: binary_sensor.window_office
            state: "on"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_office_desired_position
            data:
              value: 0
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: input_select.covers_mode
                state: "Forcer ouverture"
              - condition: state
                entity_id: input_select.cover_office_mode
                state: "Forcer ouverture"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_office_desired_position
            data:
              value: 100
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: input_select.covers_mode
                state: "Forcer fermeture"
              - condition: state
                entity_id: input_select.cover_office_mode
                state: "Forcer fermeture"
              - condition: state
                entity_id: input_select.period_of_day
                state: "Nuit"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_office_desired_position
            data:
              value: 0
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: input_select.cover_office_mode
                state: "Travail"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_office_desired_position
            data:
              value: 55
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: input_select.covers_mode
                state: "Petits trous"
              - condition: state
                entity_id: input_select.cover_office_mode
                state: "Petits trous"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_office_desired_position
            data:
              value: "{{ states('input_number.cover_office_accurate_position') }}"
    default:
      - if:
          - condition: state
            entity_id: input_boolean.is_night
            state: "on"
        then:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_office_desired_position
            data:
              value: 0
        else:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_office_desired_position
            data:
              value: 100
