---
description: Cover - Parents bedroom - Positioning
alias: cover_parents_bedroom_positioning
id: 826dec5e-096f-4021-a115-1801b4a89ca7
mode: restart
trigger:
  - platform: time_pattern
    minutes: "/10"
  - platform: event
    event_type:
      - timer.cancelled
      - timer.finished
    event_data:
      entity_id: timer.cover_parents_bedroom
condition:
  - condition: state
    entity_id: timer.cover_parents_bedroom
    state: "idle"
  - condition: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(states.cover.shelly_2_5_rc_parents_bedroom.last_changed) | int(0)) > (states('input_number.cover_parents_bedroom_detection') | int) }}"
action:
  - condition: template
    value_template: "{{ not is_state('input_select.covers_mode', 'Manuel') }}"
  - condition: template
    value_template: "{{ not is_state('input_select.cover_parents_bedroom_mode', 'Manuel') }}"
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.presence_at_home
            state: "off"
          - condition: state
            entity_id: binary_sensor.window_parents_bedroom
            state: "on"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_parents_bedroom_desired_position
            data:
              value: 0
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: input_select.covers_mode
                state: "Forcer ouverture"
              - condition: state
                entity_id: input_select.cover_parents_bedroom_mode
                state: "Forcer ouverture"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_parents_bedroom_desired_position
            data:
              value: 100
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: input_select.covers_mode
                state: "Forcer fermeture"
              - condition: state
                entity_id: input_select.covers_mode
                state: "Forcer fermeture - chambres"
              - condition: state
                entity_id: input_select.cover_parents_bedroom_mode
                state: "Forcer fermeture"
              - condition: state
                entity_id: input_select.period_of_day
                state: "Nuit"
              - condition: state
                entity_id: input_select.period_of_day
                state: "Nuit - chambres"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_parents_bedroom_desired_position
            data:
              value: 0
      - conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: input_select.covers_mode
                state: "Petits trous"
              - condition: state
                entity_id: input_select.cover_parents_bedroom_mode
                state: "Petits trous"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_parents_bedroom_desired_position
            data:
              value: "{{ states('input_number.cover_parents_bedroom_accurate_position') }}"
    default:
      - if:
          - condition: state
            entity_id: input_boolean.is_night
            state: "on"
        then:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_parents_bedroom_desired_position
            data:
              value: 0
        else:
          - service: input_number.set_value
            target:
              entity_id: input_number.cover_parents_bedroom_desired_position
            data:
              value: 100
