---
description: HACS update - Notify
alias: hacs_update_notify
id: ae935538-9119-456a-a75c-be62872b229b
trigger:
  - platform: state
    entity_id: sensor.hacs
condition:
  - condition: template
    value_template: "{{ states('sensor.hacs') != 'unknown' }}"
  - condition: template
    value_template: "{{ (states('sensor.hacs') | int(0)) != 0 }}"
action:
  - parallel:
      - service: notify.fabien_telegram
        data:
          message: >
            Mise à jour en attente sur HACS :
            {% for repo in state_attr('sensor.hacs', 'repositories') %}
              *{{ repo.display_name }}* _{{ repo["installed_version"] }}_ -> _{{ repo["available_version"] }}_
            {% endfor %}
      - service: hassio.addon_stdin
        data:
          addon: 15d21743_samba_backup
          input: trigger
