---
sensor:
  - default_entity_id: sensor.sun_color_temp_kelvin
    name: Température de couleur du soleil
    unique_id: '54015957-0892-4ad0-88fe-0a7666b00c96'

    unit_of_measurement: 'K'

    state: >-
      {% set elevation = min(max(state_attr('sun.sun', 'elevation') | float(0), 0), 90) %}
      {% set kelvin = 7088.41 - 5588.41 / (1 + 0.222 * elevation ** 0.81) %}
      {{ ((kelvin / 50) | round * 50) | int }}

    availability: '{{ state_attr("sun.sun", "elevation") is not none }}'
