---
sensor:
  - default_entity_id: sensor.sun_color_temp_kelvin
    name: Température de couleur du soleil
    unique_id: '54015957-0892-4ad0-88fe-0a7666b00c96'

    unit_of_measurement: 'K'

    state: '{{ (4791.67 - 3290.66/(1 + 0.222 * (min(max(state_attr("sun.sun", "elevation") | int(0), 0), 90)**0.81))) | int(0) }}'
