---
pv${pv_n}:
  power:
    id: ${inverter}_pv${pv_n}_power
    name: ${inverter} PV${pv_n} Power
  current:
    id: ${inverter}_pv${pv_n}_current
    name: ${inverter} PV${pv_n} Current
  voltage:
    id: ${inverter}_pv${pv_n}_voltage
    name: ${inverter} PV${pv_n} Voltage
  energy_today:
    id: ${inverter}_pv${pv_n}_energy_today
    name: ${inverter} PV${pv_n} Energy Today
  energy_total:
    id: ${inverter}_pv${pv_n}_energy_total
    name: ${inverter} PV${pv_n} Energy Total
