---
description: Purge recorder database
alias: recorder_purge
id: 42e864a1-fa80-4a02-88e3-53149124e6b7
mode: single
trigger:
  - platform: time_pattern
    minutes: 12
action:
  - service: recorder.purge
