---
id: teleinfo_poe_recovery
alias: Teleinfo - Redémarrage PoE
description: ''

triggers:
  - trigger: state
    entity_id: binary_sensor.jardin_teleinfo_status
    to: 'off'
    for: '00:10:00'

actions:
  - repeat:
      sequence:
        - action: button.press
          target:
            entity_id: button.usw_pro_max_24_poe_redemarrer_l_alimentation_de_teleinfo
        - wait_template: "{{ is_state('binary_sensor.jardin_teleinfo_status', 'on') }}"
          timeout: '00:10:00'
      until:
        - condition: template
          value_template: >-
            {{ is_state('binary_sensor.jardin_teleinfo_status', 'on')
               or repeat.index >= 3 }}

mode: single
max_exceeded: silent
