substitutions:
  esphome_name: teleinfo
  devicename: Teleinfo
  logger_level: info # debug pour obtenir dans les logs toutes les infos de la téléinformation
  api_encryption_key: !secret esphome_teleinfo_api_encryption_key
  api_password: !secret esphome_teleinfo_api_password

<<: !include .common.yaml

esp8266:
  board: d1_mini

logger:
  baud_rate: 0
  esp8266_store_log_strings_in_flash: false

teleinfo:
  update_interval: 10s
  historical_mode: true # false en mode standard

uart:
  id: uart_bus
  rx_pin: GPIO3
  baud_rate: 1200 # 9600 en mode standard
  parity: EVEN
  data_bits: 7

sensor:
  # Index
  - platform: teleinfo
    tag_name: "HCHP"
    name: "${devicename} - Index - Heures pleines"
    icon: mdi:gauge
    id: peak_hours
    unit_of_measurement: Wh
    device_class: "energy"
    state_class: "total_increasing"

  - platform: teleinfo
    tag_name: "HCHC"
    name: "${devicename} - Index - Heures creuses"
    icon: mdi:gauge
    id: offpeak_hours
    unit_of_measurement: Wh
    device_class: "energy"
    state_class: "total_increasing"

  # Others
  - platform: teleinfo
    tag_name: "PAPP"
    name: "${devicename} - Puissance apparente"
    icon: mdi:flash
    id: apparent_power
    state_class: "measurement"
    unit_of_measurement: VA

  - platform: teleinfo
    tag_name: "IINST"
    name: "${devicename} - Intensité"
    icon: mdi:current-ac
    id: current
    device_class: "current"
    state_class: "measurement"
    unit_of_measurement: A
